function webstockgwt(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Bc='.cache.html',$='/',gc='02659DF572FB05F6347035BCF81FF241',jc='50EA7C3B1A8517691F42F3E03835324E',kc='751A7177AB6350B41EC57381B3E1DF08',oc='96E485AE6FF284B1E67DFB06C0AF9926',Ac=':',hc=':1',qc=':10',rc=':11',sc=':12',tc=':13',uc=':14',ic=':2',lc=':3',mc=':4',nc=':5',vc=':6',wc=':7',xc=':8',yc=':9',nb='::',Jc='<script defer="defer">webstockgwt.onInjectionDone(\'webstockgwt\')<\/script>',gb='<script id="',qb='=',Z='?',sb='Bad handler "',pc='D983C5871863F686C531C3F8CB3714BD',Ic='DOMContentLoaded',zc='F4A78EA3CB7254BB6E610C95BE36FF96',ib='SCRIPT',fb='__gwt_marker_webstockgwt',Vb='adobeair',Wb='air',jb='base',bb='baseUrl',S='begin',R='bootstrap',Bb='chrome',ab='clear.cache.gif',pb='content',X='end',Rb='gecko',Tb='gecko1_8',Ub='gecko1_9',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',Cc='gwt/clean/clean.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',Ab='gxt.user.agent',Hc='head',ec='hosted.html?webstockgwt',Gc='href',Fb='ie6',Hb='ie7',Jb='ie8',Kb='ie9',wb='iframe',_='img',xb="javascript:''",Dc='link',_b='linux',dc='loadExternalRefs',$b='mac',Zb='mac os x',Yb='macintosh',kb='meta',zb='moduleRequested',W='moduleStartup',Db='msie',Eb='msie 6',Gb='msie 7',Ib='msie 8',lb='name',Cb='opera',yb='position:absolute;width:0;height:0;border:none',Ec='rel',Sb='rv:1.8',Lb='safari',Nb='safari3',Pb='safari4',Qb='safari5',cb='script',fc='selectingPermutation',Q='startup',Fc='stylesheet',eb='undefined',cc='unknown',Xb='user.agent.os',Mb='version/3',Ob='version/4',P='webstockgwt',db='webstockgwt.nocache.js',mb='webstockgwt::',bc='win32',ac='windows';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}webstockgwt=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1)return Bb;if(a.indexOf(Cb)!=-1)return Cb;if(a.indexOf(Db)!=-1){if(a.indexOf(Eb)!=-1)return Fb;if(a.indexOf(Gb)!=-1)return Hb;if(a.indexOf(Ib)!=-1)return Jb;return Kb}if(a.indexOf(Lb)!=-1){if(a.indexOf(Mb)!=-1)return Nb;if(a.indexOf(Ob)!=-1)return Pb;return Qb}if(a.indexOf(Rb)!=-1){if(a.indexOf(Sb)!=-1)return Tb;return Ub}if(a.indexOf(Vb)!=-1)return Wb;return null};u[Ab]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie6:4,ie7:5,ie8:6,ie9:7,opera:8,safari3:9,safari4:10,safari5:11};v[Xb]=function(){var a=l.navigator.userAgent.toLowerCase();if(a.indexOf(Yb)!=-1||a.indexOf(Zb)!=-1){return $b}if(a.indexOf(_b)!=-1){return _b}if(a.indexOf(ac)!=-1||a.indexOf(bc)!=-1){return ac}return cc};u[Xb]={linux:0,mac:1,windows:2};webstockgwt.onScriptLoad=function(){if(H){q=true;B()}};webstockgwt.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:dc,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=ec;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:fc});if(!A()){try{F([Jb,_b],gc);F([Jb,$b],gc+hc);F([Jb,ac],gc+ic);F([Kb,_b],jc);F([Kb,$b],jc+hc);F([Kb,ac],jc+ic);F([Fb,_b],kc);F([Fb,$b],kc+hc);F([Fb,ac],kc+ic);F([Hb,_b],kc+lc);F([Hb,$b],kc+mc);F([Hb,ac],kc+nc);F([Cb,_b],oc);F([Cb,$b],oc+hc);F([Cb,ac],oc+ic);F([Wb,_b],pc);F([Wb,$b],pc+hc);F([Pb,$b],pc+qc);F([Pb,ac],pc+rc);F([Qb,_b],pc+sc);F([Qb,$b],pc+tc);F([Qb,ac],pc+uc);F([Wb,ac],pc+ic);F([Bb,_b],pc+lc);F([Bb,$b],pc+mc);F([Bb,ac],pc+nc);F([Nb,_b],pc+vc);F([Nb,$b],pc+wc);F([Nb,ac],pc+xc);F([Pb,_b],pc+yc);F([Tb,_b],zc);F([Tb,$b],zc+hc);F([Tb,ac],zc+ic);F([Ub,_b],zc+lc);F([Ub,$b],zc+mc);F([Ub,ac],zc+nc);J=w[G(Ab)][G(Xb)];var L=J.indexOf(Ac);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Bc}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[Cc]){var a=m.createElement(Dc);__gwt_stylesLoaded[Cc]=a;a.setAttribute(Ec,Fc);a.setAttribute(Gc,s+Cc);m.getElementsByTagName(Hc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Ic,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(Ic,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:dc,millis:(new Date).getTime(),type:S});m.write(Jc)}
webstockgwt();